# Generated by Django 4.2.9 on 2024-02-02 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsarticle",
            name="content",
            field=models.TextField(blank=True, null=True),
        ),
    ]
